AUTO_BRANCH = "g4s-auto"
NO_WATCHER = False
NO_SESSION_CLOSURE = False
NO_FIX_LIMITATION = False
CONFIG_FILE_NAME = "settings.yml"
DATA_FILE_NAME = ".variables.dat"
IDENTITY_FILE_NAME = "IDENTITY.json"
